player: spotify
ignoreErrors: false
timerInterval: 200
updateInterval: 2000
style:
  hAlignment: center
  before:
    background: ""
    foreground: "#555555"
    bold: false
    italic: false
    underline: false
    strikethrough: false
    blink: false
    faint: true
  current:
    background: ""
    foreground: "#89b4fa"
    bold: true
    italic: true
    underline: false
    strikethrough: false
    blink: false
    faint: false
  after:
    background: ""
    foreground: "#555555"
    bold: false
    italic: false
    underline: false
    strikethrough: false
    blink: false
    faint: true
pipe:
  length: 60
  overflow: word
mpd:
  address: 127.0.0.1:6600
  password: ""
mopidy:
  address: 127.0.0.1:6680
mpris:
  players: [spotify]
browser:
  port: 8974
local:
  folder: ""